// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/SergeyBogomolovv/profile-manager/notification/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NotifySubsRepo is an autogenerated mock type for the NotifySubsRepo type
type NotifySubsRepo struct {
	mock.Mock
}

type NotifySubsRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *NotifySubsRepo) EXPECT() *NotifySubsRepo_Expecter {
	return &NotifySubsRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, userID, subType
func (_m *NotifySubsRepo) Delete(ctx context.Context, userID string, subType domain.SubscriptionType) error {
	ret := _m.Called(ctx, userID, subType)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SubscriptionType) error); ok {
		r0 = rf(ctx, userID, subType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifySubsRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type NotifySubsRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - subType domain.SubscriptionType
func (_e *NotifySubsRepo_Expecter) Delete(ctx interface{}, userID interface{}, subType interface{}) *NotifySubsRepo_Delete_Call {
	return &NotifySubsRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, subType)}
}

func (_c *NotifySubsRepo_Delete_Call) Run(run func(ctx context.Context, userID string, subType domain.SubscriptionType)) *NotifySubsRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.SubscriptionType))
	})
	return _c
}

func (_c *NotifySubsRepo_Delete_Call) Return(_a0 error) *NotifySubsRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotifySubsRepo_Delete_Call) RunAndReturn(run func(context.Context, string, domain.SubscriptionType) error) *NotifySubsRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// IsExists provides a mock function with given fields: ctx, userID, subType
func (_m *NotifySubsRepo) IsExists(ctx context.Context, userID string, subType domain.SubscriptionType) (bool, error) {
	ret := _m.Called(ctx, userID, subType)

	if len(ret) == 0 {
		panic("no return value specified for IsExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SubscriptionType) (bool, error)); ok {
		return rf(ctx, userID, subType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SubscriptionType) bool); ok {
		r0 = rf(ctx, userID, subType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.SubscriptionType) error); ok {
		r1 = rf(ctx, userID, subType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotifySubsRepo_IsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExists'
type NotifySubsRepo_IsExists_Call struct {
	*mock.Call
}

// IsExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - subType domain.SubscriptionType
func (_e *NotifySubsRepo_Expecter) IsExists(ctx interface{}, userID interface{}, subType interface{}) *NotifySubsRepo_IsExists_Call {
	return &NotifySubsRepo_IsExists_Call{Call: _e.mock.On("IsExists", ctx, userID, subType)}
}

func (_c *NotifySubsRepo_IsExists_Call) Run(run func(ctx context.Context, userID string, subType domain.SubscriptionType)) *NotifySubsRepo_IsExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.SubscriptionType))
	})
	return _c
}

func (_c *NotifySubsRepo_IsExists_Call) Return(_a0 bool, _a1 error) *NotifySubsRepo_IsExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotifySubsRepo_IsExists_Call) RunAndReturn(run func(context.Context, string, domain.SubscriptionType) (bool, error)) *NotifySubsRepo_IsExists_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, userID, subType
func (_m *NotifySubsRepo) Save(ctx context.Context, userID string, subType domain.SubscriptionType) error {
	ret := _m.Called(ctx, userID, subType)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SubscriptionType) error); ok {
		r0 = rf(ctx, userID, subType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifySubsRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type NotifySubsRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - subType domain.SubscriptionType
func (_e *NotifySubsRepo_Expecter) Save(ctx interface{}, userID interface{}, subType interface{}) *NotifySubsRepo_Save_Call {
	return &NotifySubsRepo_Save_Call{Call: _e.mock.On("Save", ctx, userID, subType)}
}

func (_c *NotifySubsRepo_Save_Call) Run(run func(ctx context.Context, userID string, subType domain.SubscriptionType)) *NotifySubsRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.SubscriptionType))
	})
	return _c
}

func (_c *NotifySubsRepo_Save_Call) Return(_a0 error) *NotifySubsRepo_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotifySubsRepo_Save_Call) RunAndReturn(run func(context.Context, string, domain.SubscriptionType) error) *NotifySubsRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SubscriptionsByUser provides a mock function with given fields: ctx, userID
func (_m *NotifySubsRepo) SubscriptionsByUser(ctx context.Context, userID string) ([]domain.Subscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SubscriptionsByUser")
	}

	var r0 []domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Subscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Subscription); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotifySubsRepo_SubscriptionsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscriptionsByUser'
type NotifySubsRepo_SubscriptionsByUser_Call struct {
	*mock.Call
}

// SubscriptionsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *NotifySubsRepo_Expecter) SubscriptionsByUser(ctx interface{}, userID interface{}) *NotifySubsRepo_SubscriptionsByUser_Call {
	return &NotifySubsRepo_SubscriptionsByUser_Call{Call: _e.mock.On("SubscriptionsByUser", ctx, userID)}
}

func (_c *NotifySubsRepo_SubscriptionsByUser_Call) Run(run func(ctx context.Context, userID string)) *NotifySubsRepo_SubscriptionsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *NotifySubsRepo_SubscriptionsByUser_Call) Return(_a0 []domain.Subscription, _a1 error) *NotifySubsRepo_SubscriptionsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NotifySubsRepo_SubscriptionsByUser_Call) RunAndReturn(run func(context.Context, string) ([]domain.Subscription, error)) *NotifySubsRepo_SubscriptionsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, subType, enabled
func (_m *NotifySubsRepo) Update(ctx context.Context, userID string, subType domain.SubscriptionType, enabled bool) error {
	ret := _m.Called(ctx, userID, subType, enabled)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.SubscriptionType, bool) error); ok {
		r0 = rf(ctx, userID, subType, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifySubsRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type NotifySubsRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - subType domain.SubscriptionType
//   - enabled bool
func (_e *NotifySubsRepo_Expecter) Update(ctx interface{}, userID interface{}, subType interface{}, enabled interface{}) *NotifySubsRepo_Update_Call {
	return &NotifySubsRepo_Update_Call{Call: _e.mock.On("Update", ctx, userID, subType, enabled)}
}

func (_c *NotifySubsRepo_Update_Call) Run(run func(ctx context.Context, userID string, subType domain.SubscriptionType, enabled bool)) *NotifySubsRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.SubscriptionType), args[3].(bool))
	})
	return _c
}

func (_c *NotifySubsRepo_Update_Call) Return(_a0 error) *NotifySubsRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotifySubsRepo_Update_Call) RunAndReturn(run func(context.Context, string, domain.SubscriptionType, bool) error) *NotifySubsRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotifySubsRepo creates a new instance of NotifySubsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifySubsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotifySubsRepo {
	mock := &NotifySubsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
