// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/SergeyBogomolovv/profile-manager/notification/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// SetupUserRepo is an autogenerated mock type for the SetupUserRepo type
type SetupUserRepo struct {
	mock.Mock
}

type SetupUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *SetupUserRepo) EXPECT() *SetupUserRepo_Expecter {
	return &SetupUserRepo_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, userID
func (_m *SetupUserRepo) GetByID(ctx context.Context, userID string) (domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetupUserRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type SetupUserRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SetupUserRepo_Expecter) GetByID(ctx interface{}, userID interface{}) *SetupUserRepo_GetByID_Call {
	return &SetupUserRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID)}
}

func (_c *SetupUserRepo_GetByID_Call) Run(run func(ctx context.Context, userID string)) *SetupUserRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SetupUserRepo_GetByID_Call) Return(_a0 domain.User, _a1 error) *SetupUserRepo_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SetupUserRepo_GetByID_Call) RunAndReturn(run func(context.Context, string) (domain.User, error)) *SetupUserRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTelegramID provides a mock function with given fields: ctx, telegramID
func (_m *SetupUserRepo) GetByTelegramID(ctx context.Context, telegramID int64) (domain.User, error) {
	ret := _m.Called(ctx, telegramID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTelegramID")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.User, error)); ok {
		return rf(ctx, telegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.User); ok {
		r0 = rf(ctx, telegramID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, telegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetupUserRepo_GetByTelegramID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTelegramID'
type SetupUserRepo_GetByTelegramID_Call struct {
	*mock.Call
}

// GetByTelegramID is a helper method to define mock.On call
//   - ctx context.Context
//   - telegramID int64
func (_e *SetupUserRepo_Expecter) GetByTelegramID(ctx interface{}, telegramID interface{}) *SetupUserRepo_GetByTelegramID_Call {
	return &SetupUserRepo_GetByTelegramID_Call{Call: _e.mock.On("GetByTelegramID", ctx, telegramID)}
}

func (_c *SetupUserRepo_GetByTelegramID_Call) Run(run func(ctx context.Context, telegramID int64)) *SetupUserRepo_GetByTelegramID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *SetupUserRepo_GetByTelegramID_Call) Return(_a0 domain.User, _a1 error) *SetupUserRepo_GetByTelegramID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SetupUserRepo_GetByTelegramID_Call) RunAndReturn(run func(context.Context, int64) (domain.User, error)) *SetupUserRepo_GetByTelegramID_Call {
	_c.Call.Return(run)
	return _c
}

// IsExists provides a mock function with given fields: ctx, userID
func (_m *SetupUserRepo) IsExists(ctx context.Context, userID string) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetupUserRepo_IsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExists'
type SetupUserRepo_IsExists_Call struct {
	*mock.Call
}

// IsExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SetupUserRepo_Expecter) IsExists(ctx interface{}, userID interface{}) *SetupUserRepo_IsExists_Call {
	return &SetupUserRepo_IsExists_Call{Call: _e.mock.On("IsExists", ctx, userID)}
}

func (_c *SetupUserRepo_IsExists_Call) Run(run func(ctx context.Context, userID string)) *SetupUserRepo_IsExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SetupUserRepo_IsExists_Call) Return(_a0 bool, _a1 error) *SetupUserRepo_IsExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SetupUserRepo_IsExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *SetupUserRepo_IsExists_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *SetupUserRepo) Update(ctx context.Context, user domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetupUserRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SetupUserRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *SetupUserRepo_Expecter) Update(ctx interface{}, user interface{}) *SetupUserRepo_Update_Call {
	return &SetupUserRepo_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *SetupUserRepo_Update_Call) Run(run func(ctx context.Context, user domain.User)) *SetupUserRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *SetupUserRepo_Update_Call) Return(_a0 error) *SetupUserRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SetupUserRepo_Update_Call) RunAndReturn(run func(context.Context, domain.User) error) *SetupUserRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewSetupUserRepo creates a new instance of SetupUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSetupUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SetupUserRepo {
	mock := &SetupUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
