// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TokenRepo is an autogenerated mock type for the TokenRepo type
type TokenRepo struct {
	mock.Mock
}

type TokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenRepo) EXPECT() *TokenRepo_Expecter {
	return &TokenRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID
func (_m *TokenRepo) Create(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TokenRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *TokenRepo_Expecter) Create(ctx interface{}, userID interface{}) *TokenRepo_Create_Call {
	return &TokenRepo_Create_Call{Call: _e.mock.On("Create", ctx, userID)}
}

func (_c *TokenRepo_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *TokenRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TokenRepo_Create_Call) Return(_a0 string, _a1 error) *TokenRepo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenRepo_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID) (string, error)) *TokenRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// UserID provides a mock function with given fields: ctx, token
func (_m *TokenRepo) UserID(ctx context.Context, token string) (uuid.UUID, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for UserID")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenRepo_UserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserID'
type TokenRepo_UserID_Call struct {
	*mock.Call
}

// UserID is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *TokenRepo_Expecter) UserID(ctx interface{}, token interface{}) *TokenRepo_UserID_Call {
	return &TokenRepo_UserID_Call{Call: _e.mock.On("UserID", ctx, token)}
}

func (_c *TokenRepo_UserID_Call) Run(run func(ctx context.Context, token string)) *TokenRepo_UserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TokenRepo_UserID_Call) Return(_a0 uuid.UUID, _a1 error) *TokenRepo_UserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenRepo_UserID_Call) RunAndReturn(run func(context.Context, string) (uuid.UUID, error)) *TokenRepo_UserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenRepo creates a new instance of TokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenRepo {
	mock := &TokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
