with-expecter: True
dir: '{{.InterfaceDir}}/mocks'
outpkg: mocks
filename: '{{.InterfaceName}}.go'
mockname: '{{.InterfaceName}}'
resolve-type-alias: False
disable-version-string: True
issue-845-fix: True
packages:
  github.com/SergeyBogomolovv/profile-manager/sso/internal/controller:
    interfaces:
      AuthService:
  github.com/SergeyBogomolovv/profile-manager/sso/internal/service:
    interfaces:
      Broker:
      TokenRepo:
      UserRepo:
