with-expecter: True
dir: '{{.InterfaceDir}}/mocks'
outpkg: mocks
filename: '{{.InterfaceName}}.go'
mockname: '{{.InterfaceName}}'
resolve-type-alias: False
disable-version-string: True
issue-845-fix: True
packages:
  github.com/SergeyBogomolovv/profile-manager/notification/internal/mailer:
    interfaces:
      Mailer:
  github.com/SergeyBogomolovv/profile-manager/notification/internal/service:
    interfaces:
      SetupTokenRepo:
      SetupUserRepo:
      SetupSubsRepo:
      Sender:
      NotifyUserRepo:
      NotifySubsRepo:
  github.com/SergeyBogomolovv/profile-manager/notification/internal/controller:
    interfaces:
      Service:
