name: sso

on:
  push:
    branches:
      - main
    paths:
      - 'sso/**'
      - 'common/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Setup Go Workspace
        run: go work sync

      - name: Test
        working-directory: ./sso
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: grekas/profile-manager-sso:latest
          context: .
          file: ./sso/Dockerfile
